import Head from 'next/head'
import Image from 'next/image'
import home from '../styles/Home.module.scss'

// const prefix = process.env.NEXT_PUBLIC_BASE_PATH || '';

export default function Home() {
  console.log(process.env.NEXT_PUBLIC_BASE_PATH)
  return (
    <div className={home.container}>
      <Head>
        <title>Create Next App</title>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/JuniorCaucusWhite.png" />
      </Head>

      <div className={home.content}>
        <nav className="main-nav">
          <a href="#">Home</a>
          <a href="#">Newsletters</a>
          <a href="#">Opportunities</a>
          <a href="#">About</a>
          <a href="#">Logo Logo Logo</a>
        </nav>

        <section className={home.cardcontainer}>
          <img className={home.cardstuyimg} src="/stuy.jpg"/>
          <img className={home.cardlogo} src="/JuniorCaucusWhite.png"/>
        </section>

        <footer className={home.footer}>
          &copy; Stuyvesant Junior Caucus 2021, Designed by Paul and Myles
        </footer>
      </div>
    </div>
  )
}
